### PR TITLE
Upgrade Chokidar from 2.0.0 to 3.0.0

### PR DESCRIPTION
**Pull request by ehmicky**
Chokidar 3.0.0 is mostly a big refactoring with several bug fixes.

### CODE REVIEW

**Comment by phated** [comment]
It drops support for our support matrix. This would be a breaking change for us.

**Comment by ehmicky** [comment]
Oh I see.

Why is Gulp supporting Node.js down to `0.10`? Node.js itself does not support anything below `8`.

This has the side effect of not updating any dependencies (since most libraries support only `>6` or `>8`). So you can't get the bug fixes and security fixes from new releases. For example if one dependency was to have a security vulnerability issue, the fix could not be used in `glob-watcher` without breaking the Node.js `0.10` support.

**Comment by phated** [comment]
Because gulp 4 was in development before iojs even happened and a not insignificant amount of users are stuck on node 0.10

We take security notices very seriously, and even take on dependencies in our chain so we can maintain our support matrix. Gulp is a development tool so many security alerts don't affect it the way they would in production/server environments.

**Comment by ehmicky** [comment]
Just out curiosity, how do you keep track of Gulp users Node.js versions?

For reference, last year's Node.js version download:

downloads-by-version

**Comment by phated** [comment]
I have notifications set for all sorts of projects that indicate the level of node 0.10/0.12 users, especially when those projects accidentally break those users within their semver range.

**Comment by ehmicky** [comment]
Where do you get this data from? I am curious because I would like to know for my own projects.

The `npm` API is undocumented, but even then I am not sure it gives out this information (does it?).

**Comment by phated** [comment]
I'm not sure what information npm collects or provides but one indicator I use is issues on popular stream modules. In one instance, through2 accidentally broke old node support without a major bump and users created/commented on an issue about it.

**Comment by ehmicky** [comment]
Yes exactly that was my guess: through GitHub issues. But that's not so representative as it emphasized outliers. Namely if you have 10 users on an old Node.js version, you will hear from them, but not from the 10000 users that are on newer versions.

I just wish `npm` provided with a more accurate way to check this for library authors.

**Comment by simison** [comment]
Would it be possible to leave a version of Gulp with Node.js 0.10  support available in a maintenance mode (e.g. `4.0.x`), as in promise to do security updates for them but be able to move onwards with the rest of the world otherwise via `4.1.x` and up?

**Comment by phated** [comment]
@simison no, that's not how semver works. You have to bump whole major version for breaking changes.

**Pull request closed without merging**
